---
- hosts: servers
  sudo: yes
  vars_files:
      - vars/main.yml
  roles:
      #    - role: geerlingguy.mysql
  tasks:
    - name: yum install repos
      yum: name={{item}}
      with_items:
        - http://ftp-srv2.kddilabs.jp/Linux/distributions/fedora/epel/6/x86_64/epel-release-6-8.noarch.rpm
        - http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
        - http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
        - http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm
    - name: be sure httpd is installed
      yum: name=httpd state=installed enablerepo=remi,epel

    - name: be sure httpd is running and enabled
      service: name=httpd state=running enabled=yes

    - name: be sure mysqld is installed
      yum: name={{ item }} state=installed enablerepo=mysql-*
      with_items:
        - mysql
        - mysql-server
        - mysql-devel
        - MySQL-python
      tags: mysqld

    - name: be sure mysqld is running and enabled
      service: name=mysqld state=running enabled=yes
      tags: mysqld

    - name: Create database
      mysql_db: db={{ item }} state=present encoding=utf8
      with_items:
        - test01_dev
        - test01_test
      tags: mysqld
    - name: Create database user
      mysql_user: >
        name=test01user
        password=test01pass
        priv=*.*:ALL
        state=present
      tags: mysqld
